FROM r-base

RUN apt-get update && apt-get -y install {{{dependencies.system}}}

RUN install2.r --error {{{dependencies.CRAN}}}
{{{#dependencies.github}}}
RUN installGithub.r {{{dependencies.github}}}
{{{/dependencies.github}}}

COPY scripts /usr/local/bin/

WORKDIR /root
CMD bash
