#!/bin/sh
cat >> ~/.Rprofile <<EOF
library(testthat)
devtools::load_all()
setwd("tests/testthat")
local({
  for (f in list.files(".", pattern="^helper")) {
    message("Reading ", f)
    sys.source(f, .GlobalEnv)
  }})
EOF

R
